// Generated by CoffeeScript 1.3.2-pre
(function() {

  // include core;

  MKExports(PRIVATE_NAMESPACE, 'init', this, function(options, callback) {
    var app;
    app = new Application;
    return app.load(options, callback);
  });

}).call(this);
