// Generated by CoffeeScript 1.3.2-pre
(function() {
  var api;

  api = window[PRIVATE_NAMESPACE];

  api || (api = {});

  api['init'] = function(options, callback) {
    var app;
    app = new Application;
    return app.load(options, callback);
  };

}).call(this);
